CREATE TABLE Users(PRIMARY KEY UserID VARCHAR(20), Country VARCHAR(20), Address VARCHAR(50), BidderRating INT, SellerRating INT);
CREATE TABLE Items(PRIMARY KEY ItemID BIGINT, FOREIGN KEY UserID VARCHAR(20), ItemName VARCHAR(50), FirstBid DECIMAL(8,2), BuyPrice DECIMAL(8,2), NumberOfBids INT, Description VARCHAR(4000));
CREATE TABLE ItemCategory(PRIMARY KEY ItemID BIGINT, Category VARCHAR(20));
CREATE TABLE ItemStarted(PRIMARY KEY ItemID BIGINT, Started DATETIME);
CREATE TABLE ItemEnds(PRIMARY KEY ItemID BIGINT, Ends DATETIME);
CREATE TABLE Bids(PRIMARY KEY UserID VARCHAR(20), FOREIGN KEY ItemID BIGINT, BidTime DATETIME, Amount DECIMAL(8,2));
