CREATE TABLE Users
(
	PRIMARY KEY UserID VARCHAR(20), 
	Country VARCHAR(20), 
	Address VARCHAR(50), 
	SellerRating INT
);

CREATE TABLE Items
(
	PRIMARY KEY ItemID BIGINT, 
	FOREIGN KEY UserID VARCHAR(20), 
	ItemName VARCHAR(50), 
	FirstBid DECIMAL(8,2), 
	BuyPrice DECIMAL(8,2),
	CurrentHighestBid DECIMAL(8,2),
	StartTime TIMESTAMP,
	EndTime TIMESTAMP,
	NumberOfBids INT, 
	Description VARCHAR(4000)
);

CREATE TABLE ItemCategory
(
	PRIMARY KEY ItemID BIGINT, 
	Category VARCHAR(20)
);

CREATE TABLE Bids
(
	PRIMARY KEY UserID VARCHAR(20), 
	FOREIGN KEY ItemID BIGINT, 
	BidTime TIMESTAMP, 
	Amount DECIMAL(8,2)
);
