LOAD DATA LOCAL INFILE 'users.dat' INTO TABLE Users
FIELDS TERMINATED BY '|*|' ENCLOSED BY '"';

LOAD DATA LOCAL INFILE 'items.dat' INTO TABLE Items
FIELDS TERMINATED BY '|*|' ENCLOSED BY '"';

LOAD DATA LOCAL INFILE 'categories.dat' INTO TABLE ItemCategory
FIELDS TERMINATED BY '|*|' ENCLOSED BY '"';

LOAD DATA LOCAL INFILE 'bid.dat' INTO TABLE Bids
FIELDS TERMINATED BY '|*|' ENCLOSED BY '"';